### ISSUE TITLE
add-on you installed failed to load on startup Macos

### ISSUE THREAD

**Issue by howarddo2208** [migaku-official/Migaku-Anki-Addon#42] opened 2022-11-24 16:16 UTC
I installed addon on my anki, upon startup I received this
![image](https://user-images.githubusercontent.com/62332195/203827726-f6f44c65-bcf0-4a77-b4eb-12f617531008.png)
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Migaku Anki Add-on⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/__init__.py", line 38, in <module>
    from . import (
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/welcome_wizard.py", line 9, in <module>
    from .global_hotkeys import HotkeyConfigWidget, hotkey_handler
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/global_hotkeys.py", line 4, in <module>
    import pynput.keyboard
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/lib/shared/pynput/_util/__init__.py", line 77, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import) (/Users/tanhopdo/Library/Application Support/Anki2/addons21/1846879528/lib/macos/objc/__init__.py)

Try one of the following resolutions:

 * Please make sure that you have Python bindings for the system frameworks installed
 ```
I've tried allow accessibility like #18 for anki even though it didn't prompt
![image](https://user-images.githubusercontent.com/62332195/203828470-a1ddfadb-c1b8-4725-9d6d-3722eac6763b.png)

## System
MacBook Pro 15' 2018
macOs Ventura 13.0.1 (22A400)

## Anki
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

At the mean time I will try downgrade anki as a workaround

**Comment by MinmoTech** [comment] 2023-06-10 16:24
Duplicate of https://github.com/migaku-official/Migaku-Anki-Addon/issues/46

We will work on this soon!

**Closed by MinmoTech** 2023-06-10 16:24 UTC
